name: llvmdev_builder

on:
  pull_request:
    paths:
      - .github/workflows/llvmdev_win_builder.yml
  workflow_dispatch:
    inputs:
      recipe:
        description: "Recipe to build"
        default: "llvmdev"
        required: true
        type: choice
        options:
          - "llvmdev"
          - "llvmdev_manylinux"

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to master will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:

  windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        recipe: [llvmdev, llvmdev_manylinux]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""

      - name: Install conda-build
        run: |
          conda install conda-build

      - name: Build conda package
        env:
          CONDA_CHANNEL_DIR: conda_channel_dir
        run: |
          mkdir $CONDA_CHANNEL_DIR
          conda build ./conda-recipes/${{ matrix.recipe }} --output-folder=$CONDA_CHANNEL_DIR
          ls -lah $CONDA_CHANNEL_DIR

      - name: Upload conda package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.recipe }}-${{ runner.os }}
          path: conda_channel_dir
          compression-level: 0
          retention-days: 7
          if-no-files-found: error
          run-post: false

      - name: Get Workflow Run ID
        run: |
          echo "Current workflow run ID: ${{ github.run_id }}"
          echo "Use this ID when triggering llvmlite workflow"
