name: lint with pre-commit

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pre-commit
        run: |
          source "${CONDA}/etc/profile.d/conda.sh"
          # avoid future conflicts with base environment
          conda create --name pre-commit -c conda-forge pre-commit
          conda activate pre-commit
          echo "versions='$(python --version)-$(pre-commit --version)'" | tee -a "${GITHUB_ENV}"
      # inspired by https://github.com/pre-commit/action/blob/main/action.yml
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.versions }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Lint code with pre-commit
        run: |
          source "${CONDA}/etc/profile.d/conda.sh"
          conda activate pre-commit
          pre-commit run --verbose --all-files --show-diff-on-failure --color=always
